version: '3.2'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000"
    networks:
      - monitoring
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.portainer.frontend.rule=Host:portainer.localhost"
      - "traefik.portainer.port=9000"
      - "traefik.portainer.protocol=http"

networks:
  monitoring:

volumes:
  portainer_data:
